[package]
name = "eternal-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
eternal-format = { path = "../crates/eternal-format" }
eternal-store = { path = "../crates/eternal-store" }

[[bin]]
name = "packfile"
path = "targets/packfile.rs"
test = false
doc = false

[[bin]]
name = "segment"
path = "targets/segment.rs"
test = false
doc = false

[[bin]]
name = "cbor"
path = "targets/cbor.rs"
test = false
doc = false

[[bin]]
name = "names"
path = "targets/names.rs"
test = false
doc = false

[[bin]]
name = "records"
path = "targets/records.rs"
test = false
doc = false
